### ISSUE TITLE
Can't you view information about other nodes in the local area network?

### ISSUE THREAD

**Issue by z724133545** [hakehardware/nodemon#2]
![微信图片_20231027204030](https://github.com/hakehardware/nodemon/assets/25863016/44ac8c05-1077-434d-b20d-0d3a2ee97e39)

**Comment by hakehardware** [comment]
In order to allow this you must go into your mainnet.config.json and change to this: "grpc-private-listener": "0.0.0.0:9093",
By default the IP is 127.0.0.1 which means only local connections can query that endpoint.
